### ISSUE TITLE
Some questions about ambiguous anchor

### ISSUE THREAD

**Issue by zkyseu** [strongwolf/o2f#1]
Hi
Thanks for your wonderful work! I have a confusion about the ambiguous anchors. In o2f, you set the number of ambiguous anchors to 7. During the training process, the weight of the ambiguous anchors decreases gradually in classification loss. However, why the weight of ambiguous anchors does not decrease in GIOU loss? Do you try the experiments about decreasing the weight of ambiguous anchors in GIOU loss? Thanks for your replying!

**Comment by strongwolf** [comment]
In my opinion, weighting the regression branch is not helpful to dumplication removal beacuse the predictions are ranked by classfication scores during inference. However, I am not sure wheather weighting the regression branch in such a way as in the classificaion branch can improve the final performance. I will try the experiments soon.

**Comment by zkyseu** [comment]
Thanks! I look forward to your experimental results!

**Comment by jstacer1** [comment]
> Hi Thanks for your wonderful work! I have a confusion about the ambiguous anchors. In o2f, you set the number of ambiguous anchors to 7. During the training process, the weight of the ambiguous anchors decreases gradually in classification loss. However, why the weight of ambiguous anchors does not decrease in GIOU loss? Do you try the experiments about decreasing the weight of ambiguous anchors in GIOU loss? Thanks for your replying!

Hi,May I ask what the results of the experiment are now?

**Comment by jstacer1** [comment]
> In my opinion, weighting the regression branch is not helpful to dumplication removal beacuse the predictions are ranked by classfication scores during inference. However, I am not sure wheather weighting the regression branch in such a way as in the classificaion branch can improve the final performance. I will try the experiments soon.
Hi,May I ask what the results of the experiment are now?
