### ISSUE TITLE
Question about the use of ambiguous anchor in DETR-Based Object Detectors

### ISSUE THREAD

**Issue by ykq527** [strongwolf/o2f#2]
Hi
Thanks for your wonderful work! I was curious if you have attempted to integrate ambiguous anchor into DETR-Based detector models like DAB-DETR. If so, I would love to hear about any results or insights that the you have gained through this process.
Thank you for your time and consideration, and I look forward to your response.

**Comment by strongwolf** [comment]
We have roughly tried similar attempts which gradually decrease the number of positive samples from 'many' to 'one'  in Deformable DETR,  and without carefull tuning, we achieve similar results with Hybrid-DETR.

**Comment by ykq527** [comment]
Thanks
