### ISSUE TITLE
When I inference CrowdHuman, there was an error here

### ISSUE THREAD

**Issue by GarlicPineapple** [strongwolf/o2f#3]
`'hbox':res['bbox_vis'], # here is wrong, but no matter`
**error**
![image](https://user-images.githubusercontent.com/114122968/232801045-5a5ae91c-bdf3-4336-9376-c6b88d4d4f53.png)
I want to know how can I inference this, thanks

**Comment by strongwolf** [comment]
I think this is due to your dataset since this code is OK for me. You can change this line to 'hbox':res['bbox'],  and try again.

**Comment by GarlicPineapple** [comment]
My problem has been resolved, perhaps there was an error when I converted odgt to json, thanks
