### ISSUE TITLE
what version?

### ISSUE THREAD

**Issue by hskfn** [strongwolf/o2f#4]
Please,Can you tell me which your version of mmdet? In a few day,I apply the newest version.However, the project can't run and always emerge many debugs. Hope for your reply

**Comment by jstacer1** [comment]
> Please,Can you tell me which your version of mmdet? In a few day,I apply the newest version.However, the project can't run and always emerge many debugs. Hope for your reply
HI,May I ask how you solved it?

**Comment by jstacer1** [comment]
> Please,Can you tell me which your version of mmdet? In a few day,I apply the newest version.However, the project can't run and always emerge many debugs. Hope for your reply

I meet the same issue,how can you solve it? Hope for your reply

**Comment by hskfn** [comment]
mmdet=2.22.0;mmcv-full=1.4.0;mmengine=0.8.3;torch=1.8.0+cu111;torchvision=0.9.0+cu111
&nbsp;


听都好听
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月30日(星期六) 晚上10:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [strongwolf/o2f] what version? (Issue #4)





  
Please,Can you tell me which your version of mmdet? In a few day,I apply the newest version.However, the project can't run and always emerge many debugs. Hope for your reply
  
I meet the same issue,how can you solve it? Hope for your reply

**Comment by hskfn** [comment]
mmdet=2.22.0;mmcv-full=1.4.0;mmengine=0.8.3;torch=1.8.0+cu111;torchvision=0.9.0+cu111

**Comment by jstacer1** [comment]
> mmdet=2.22.0;mmcv-full=1.4.0;mmengine=0.8.3;torch=1.8.0+cu111;torchvision=0.9.0+cu111 &nbsp;

thanks for your reply! but i have  solved it yesterday,my environment is:
NVIDIA GeForce RTX 3090
PyTorch: 1.10.0
Python: 3.8.0
cuda:11.3
TorchVision: 0.11.0
OpenCV: 4.9.0
MMCV: 1.4.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.24.0+7247367
